### ISSUE TITLE
CRUD demo: nothing happens when pressing New item in search mode 

### ISSUE THREAD

**Issue by paivisoinio** [vaadin/vaadin-crud#106]
1. Open CRUD demo at:
https://cdn.vaadin.com/vaadin-crud/1.0.0-alpha5/demo/#crud-basic-demos
2. Write something with no hits in any field (cannot reproduce if hits found earlier)
3. Press New item
Nothing happens. 
Console log shows JS error
<img width="1382" alt="screen shot 2018-10-14 at 22 34 44" src="https://user-images.githubusercontent.com/36551733/46921252-aa916480-d001-11e8-9169-5330eb9315eb.png">

**Comment by paivisoinio** [comment]
Applies also to other demos, not just the linked basic demo

**Comment by manolo** [comment]
I think the issue is: that grid is initialized with the first array item recieved, otherwise form is not initialized until an edit or new item happens, but in this case items array is filtered hence there is no item to initiate the form. The fix should be to initialise form at the same time than grid by calling form.configure. I am at a mobile, so no checked.

**Comment by jouni** [comment]
This is also partly a UX issue. I would assume that after creating a new item, if it does not match the filters, it will not show up in the grid. So the user might be a little confused what happened.

This was the reason that in the Bakery designs the “New” button is hidden when the search/filter is active, that the user has to clear the search/filter before they can initiate creating a new item. I wonder if we should do something similar here…

**Comment by manolo** [comment]
You are right, we need either disable button, or remove filters when a new item is created. What is the best UX?

**Comment by jouni** [comment]
Maybe we could change the content of the footer/toolbar to show the number of matching items and to have a “Clear filters” button? That would be explicit at least.

If we disable the “New” button, I fear users would not understand why it’s disabled, and we would need to provide a tooltip at least. If we remove filters when a new item is created, we might cause frustration for the user by making them re-apply the filters, if they did not expect them to disappear when creating a new item.

**Comment by manolo** [comment]
Seems a good default content for the footer, then user can override by using the footer slot.
