### ISSUE TITLE
Backdrop click doesn't generate any event

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-crud#137]
Click outside the editor doesn't generate any event, however it works similar to "Cancel".
1. When the editor is clean, backdrop click just closes the dialog.
In some cases I have to do navigation on closing the editor. 
2. When the editor is dirty, backdrop click does nothing.

**Comment by jouni** [comment]
Seems almost like a duplicate of #94

**Comment by manolo** [comment]
1.- You can listen to `editor-opened-changed`
2.- it's intentional to disable that feature when dirty, much more simple (#ffs) for first release, it will considered to cover in future versions

**Comment by manolo** [comment]
Let's continue discussion in #94
