### ISSUE TITLE
vaadin 12.0.4 has a Error: Cannot read property '__getRowModel' of undefined

### ISSUE THREAD

**Issue by a497314013** [vaadin/vaadin-crud#147]
vaadin 12.0.4 has a Error: Cannot read property '__getRowModel' of undefined, Who can tell me what should I do?  The issue #78,#1416 is closed, but no ways provided.

**Comment by web-padawan** [comment]
Sorry for leaving this without an answer. No one else has reported this recently.

Please create a new issue with a reproduction if the bug is still valid.
