### ISSUE TITLE
Delete dialog has extra scrollbar when using Material theme

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-crud#150]
<img width="446" alt="screenshot 2019-02-06 at 22 59 38" src="https://user-images.githubusercontent.com/260340/52373284-f9588380-2a62-11e9-8b9e-c1f473000126.png">

**Comment by web-padawan** [comment]
I can't reproduce this with the latest web component version so I assume it was fixed.

<img width="535" alt="crud" src="https://user-images.githubusercontent.com/10589913/110938923-493e5e80-833d-11eb-98be-291cb597de32.png">
