### ISSUE TITLE
Java API: Editor Title

### ISSUE THREAD

**Issue by anezthes** [vaadin/vaadin-crud#214]
As a Java developer I want to:
1. Change the title of the editor because "Edit item" isn't sufficient.
2. Change the title's element from an h3 to an h2 (or any other depending on my document outline) to be WCAG compliant.
3. Use Lumo's default margins for headings, because consistency is important.

**Comment by tomivirkki** [comment]
Please create separate issues for the 3 different issues. The first one seems to be about i18n, see second is about a11y and the third one is about theming.

Regarding the first point, this should already be doable with the i18n object (you can specify edit label).

Regarding the second point, the component shouldn't probably use a heading element at all. The editor may be inside the component or right under the body tag depending on the configuration.
