### ISSUE TITLE
Editor is not cleared when the dialog is closed with the Esc key

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-crud#221]
See https://github.com/vaadin/bakery-app-starter-flow-spring/issues/891 for more details.

When the editor dialog is closed via the 'Cancel' button, the CancelEvent is fired properly, which runs the code at `Crud.java:188` which ultimately clears the editor.

However, when Esc is pressed, the CancelEvent is not fired and the editor is not cleared. Later, when the 'Create/New' button is pressed, the event handler at `Crud.java:171` reads the current editor item via `e.getItem()`, finds that it is not null and edits the bean instead (this is actually weird since New should always create a new empty bean instance...).

The issue is easily reproducible in the Bakery starter, just follow the reproduce steps in the issue above.

**Comment by web-padawan** [comment]
Should be fixed by #210.
