### ISSUE TITLE
DX: Add back the row click (active item) to trigger item edit

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-crud#66]
Options:
  - Some property to enable it `edit-on-click` 
  - Just a demo to fire `edit` event on `active-item-change`

**Comment by manolo** [comment]
Note that this use case is explicitly excluded in DoD. 
We might give a solution after 1.0.0 though

**Comment by jouni** [comment]
I’m currently re-evaluating the current plan with the explicit column. It’s possibly more problematic than just relying on full-row click.

If we use `active-item`, can we make sure that the user is able to re-activate the same item repeatedly, and not have to activate some other item before? I think the current `activeItem` property is “sticky” that it only changes when the user activates another item. So can we set the `activeItem` to null/undefined (basically clear it) when the editor is opened?

**Comment by manolo** [comment]
yep, the first implementation in the prototype was taking care of reseting it when opening the editor

**Comment by manolo** [comment]
Added a demo that shows how to configure your own grid without the edit button.
