### ISSUE TITLE
DX: discuss exclude/whitelist parameters

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-crud#76]
-  Regular expression for exclude - Should be an array of excluded properties ?
    `exclude` is intentional, it works similar to `pattern` in text fields, e.g. you might want to exclude all private fields and some specific ones with this expression `exclude="^_|password"`
-  Add optional whitelist for the fields.
     what should be the preference of `excluded` `included` (btw better names for them)

Current API
```
/**
 * A regular expression string to be applied to fields that will be excluded
 * when using any of the auto-configured elements (the buit-in grid or editor)
 *
 * Default is `^_` meaning that all protected properties are excluded
 */
 exclude: {
   type: String,
   value: '^_'
 },
```

**Comment by manolo** [comment]
@legioth  @alvarezguille  any opinion

**Comment by Legioth** [comment]
My gut feeling is that `include` semantics would be more useful since that would also allow you to explicitly define the ordering. In that way, you also avoid surprises if another field is added later on for different purposes.

**Comment by manolo** [comment]
Implemented `include` in https://github.com/vaadin/vaadin-crud/pull/88

**Comment by manolo** [comment]
Implemented `include` in https://github.com/vaadin/vaadin-crud/pull/88
