### ISSUE TITLE
Inconsistent behavior when pressing Esc key inside the editor dialog

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-crud#94]
The editor can be closed with Esc key when there are no changes, but not when there are pending changes. 

The dialog should still be closable with the Esc key even when there are pending changes, and show a confirm dialog (like when pressing Cancel, which is what pressing Esc equals).

**Comment by manolo** [comment]
This is intentional in the first version because of #ffs implementation is one declarative attribute vs some blocks of code and tests.
Is this needed in 1.0, otherwise we can remove the escape feature since it's not part of DoD

**Comment by jouni** [comment]
Can be fixed right after 1.0. Would not want to leave this hanging open for long, though.

**Comment by web-padawan** [comment]
Fixed by #201 and released as part of `1.3.0`.
